# Taller Limpieza con Pandas

## Instalación de Pandas

In [2]:
%pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.1.0)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.9.0 in .\.venv\Lib\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.6 in .\.venv\Lib\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## Importar Panda y Cargar CSV

In [1]:
import pandas as pd

df = pd.read_csv("datos_para_limpiar.csv")

## Mostrar Primeras 5 Filas

In [2]:
df.head(5)

,ID,Nombre,Edad,Salario,Ciudad,Genero,Nivel,Fecha,Ingresos,Gastos,Codigo,Notas
0,1,Ana,NaN,3.955413e+03,bogota,Masculino,Bajo,2018-12-29,4030.026008,1213.936751,ABC12345,Pendiente evaluación
1,2,Maria,NaN,3.054891e+03,NaN,Femenino,alto,2011-07-16,7509.810584,6038.896355,NaN,Buen empleado
2,3,Carlos,NaN,2.928345e+08,bogota,Femenino,Bajo,2022-04-07,9106.362328,6705.724812,NaN,NaN
3,4,Maria,11.0,4.718402e+03,NaN,NaN,medio,2022-10-11,NaN,NaN,XYZ98765,NaN
4,5,Laura,94.0,7.477876e+07,cali,masculino,alto,2017-07-11,3102.167244,7570.107277,NaN,Pendiente evaluación

## La información general del DataFrame

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        100 non-null    int64
 1   Nombre    100 non-null    str
 2   Edad      50 non-null     float64
 3   Salario   65 non-null     float64
 4   Ciudad    82 non-null     str
 5   Genero    73 non-null     str
 6   Nivel     73 non-null     str
 7   Fecha     100 non-null    str
 8   Ingresos  48 non-null     float64
 9   Gastos    53 non-null     float64
 10  Codigo    69 non-null     str
 11  Notas     67 non-null     str
dtypes: float64(4), int64(1), str(7)
memory usage: 9.5 KB

## Conteo de valores Nulos

In [4]:
df.isnull().sum()

ID           0
Nombre       0
Edad        50
Salario     35
Ciudad      18
Genero      27
Nivel       27
Fecha        0
Ingresos    52
Gastos      47
Codigo      31
Notas       33
dtype: int64

# Eliminación de columnas innecesarias

In [5]:
df = df.drop(columns=["ID", "Notas"]) # Elimina columnas inecesarias

In [18]:
df.head(10)

,NOMBRE,EDAD,SALARIO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO,GENERO_Masculino,GENERO_Otro,GENERO_femenino,GENERO_masculino,CIUDAD_Bogotá,CIUDAD_Cali,CIUDAD_Medellín,UTILIDAD
0,Ana,0.515708,3.955413e+03,1.0,2018-12-29,0.328719,1213.936751,ABC12345,1,0,0,0,1,0,0,-1213.608032
1,Maria,0.515708,3.054891e+03,3.0,2011-07-16,0.726166,6038.896355,NaN,0,0,0,0,1,0,0,-6038.170189
2,Carlos,0.515708,2.928345e+08,1.0,2022-04-07,0.908518,6705.724812,NaN,0,0,0,0,1,0,0,-6704.816294
3,Maria,0.096491,4.718402e+03,2.0,2022-10-11,NaN,NaN,XYZ98765,0,0,1,0,1,0,0,NaN
4,Laura,0.824561,7.477876e+07,3.0,2017-07-11,0.222743,7570.107277,NaN,0,0,0,1,0,1,0,-7569.884534
5,Juan,0.515708,1.894348e+08,NaN,2021-12-29,NaN,NaN,XYZ98765,0,0,0,0,0,1,0,NaN
6,Juan,0.385965,1.407398e+07,2.0,2010-11-21,0.185977,NaN,ABC12345,0,0,1,0,0,1,0,NaN
7,Laura,0.666667,1.407398e+07,2.0,2013-11-18,NaN,6624.491298,XYZ98765,0,0,0,0,1,0,0,NaN
8,Laura,0.515708,1.937890e+08,1.0,2025-06-02,0.480195,5852.075127,LMN24680,0,0,1,0,0,1,0,-5851.594932
9,Luis,0.515708,1.407398e+07,2.0,2015-02-08,NaN,2822.485163,NaN,0,0,1,0,1,0,0,NaN

# Normalización de nombres de columnas

In [6]:
df.columns = df.columns.str.strip().str.upper().str.replace(" ",
"_").str.replace("á", "a").str.replace("é", "e")

In [7]:
df.head(5)

,NOMBRE,EDAD,SALARIO,CIUDAD,GENERO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO
0,Ana,NaN,3.955413e+03,bogota,Masculino,Bajo,2018-12-29,4030.026008,1213.936751,ABC12345
1,Maria,NaN,3.054891e+03,NaN,Femenino,alto,2011-07-16,7509.810584,6038.896355,NaN
2,Carlos,NaN,2.928345e+08,bogota,Femenino,Bajo,2022-04-07,9106.362328,6705.724812,NaN
3,Maria,11.0,4.718402e+03,NaN,NaN,medio,2022-10-11,NaN,NaN,XYZ98765
4,Laura,94.0,7.477876e+07,cali,masculino,alto,2017-07-11,3102.167244,7570.107277,NaN

In [8]:
# Eliminar espacios y unificar mayúsculas y minúsculas
df["CIUDAD"] = df["CIUDAD"].str.strip().str.lower()

# Corregir los nombres de las ciudades
df["CIUDAD"] = df["CIUDAD"].replace({
    "bogota": "Bogotá",
    "bogotá": "Bogotá",
    "medellin": "Medellín",
    "medellín": "Medellín",
    "cali": "Cali"
})

# Verificar los resultados
print(df["CIUDAD"].value_counts(dropna=False))

CIUDAD
Bogotá      41
Cali        21
Medellín    20
NaN         18
Name: count, dtype: int64

In [9]:
df.head(5)

,NOMBRE,EDAD,SALARIO,CIUDAD,GENERO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO
0,Ana,NaN,3.955413e+03,Bogotá,Masculino,Bajo,2018-12-29,4030.026008,1213.936751,ABC12345
1,Maria,NaN,3.054891e+03,NaN,Femenino,alto,2011-07-16,7509.810584,6038.896355,NaN
2,Carlos,NaN,2.928345e+08,Bogotá,Femenino,Bajo,2022-04-07,9106.362328,6705.724812,NaN
3,Maria,11.0,4.718402e+03,NaN,NaN,medio,2022-10-11,NaN,NaN,XYZ98765
4,Laura,94.0,7.477876e+07,Cali,masculino,alto,2017-07-11,3102.167244,7570.107277,NaN

# Tratamiento de valores nulos

In [10]:
# Edad: media de edades válidas entre 0 y 120
media_edad = df.loc[df["EDAD"].between(0, 120), "EDAD"].mean()
df["EDAD"] = df["EDAD"].fillna(media_edad)

# Salario: mediana
df["SALARIO"] = df["SALARIO"].fillna(df["SALARIO"].median())

# Ciudad: moda
df["CIUDAD"] = df["CIUDAD"].fillna(df["CIUDAD"].mode()[0])

# Género: moda
df["GENERO"] = df["GENERO"].fillna(df["GENERO"].mode()[0])

# Mostrar resultado
df.head(10)

,NOMBRE,EDAD,SALARIO,CIUDAD,GENERO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO
0,Ana,58.790698,3.955413e+03,Bogotá,Masculino,Bajo,2018-12-29,4030.026008,1213.936751,ABC12345
1,Maria,58.790698,3.054891e+03,Bogotá,Femenino,alto,2011-07-16,7509.810584,6038.896355,NaN
2,Carlos,58.790698,2.928345e+08,Bogotá,Femenino,Bajo,2022-04-07,9106.362328,6705.724812,NaN
3,Maria,11.000000,4.718402e+03,Bogotá,femenino,medio,2022-10-11,NaN,NaN,XYZ98765
4,Laura,94.000000,7.477876e+07,Cali,masculino,alto,2017-07-11,3102.167244,7570.107277,NaN
5,Juan,58.790698,1.894348e+08,Cali,Femenino,NaN,2021-12-29,NaN,NaN,XYZ98765
6,Juan,44.000000,1.407398e+07,Cali,femenino,medio,2010-11-21,2780.272641,NaN,ABC12345
7,Laura,76.000000,1.407398e+07,Bogotá,Femenino,medio,2013-11-18,NaN,6624.491298,XYZ98765
8,Laura,58.790698,1.937890e+08,Cali,femenino,Bajo,2025-06-02,5356.247710,5852.075127,LMN24680
9,Luis,58.790698,1.407398e+07,Bogotá,femenino,medio,2015-02-08,NaN,2822.485163,NaN

# Asegurar tipos de datos correctos

In [11]:
# Convertir EDAD a tipo numérico
df["EDAD"] = pd.to_numeric(df["EDAD"], errors="coerce")

# Convertir FECHA a formato datetime
df["FECHA"] = pd.to_datetime(df["FECHA"], errors="coerce")

# Verificar los tipos de datos
print(df.dtypes)

NOMBRE                 str
EDAD               float64
SALARIO            float64
CIUDAD                 str
GENERO                 str
NIVEL                  str
FECHA       datetime64[us]
INGRESOS           float64
GASTOS             float64
CODIGO                 str
dtype: object

# Filtrado de datos fuera de rango

In [12]:
# Eliminar registros con edades fuera del rango de 0 a 120 años
df = df[df["EDAD"].between(0, 120)]

# Eliminar registros con salarios mayores a 1.000 millones
df = df[df["SALARIO"] <= 1_000_000_000]

# Reiniciar los índices
df = df.reset_index(drop=True)

# Mostrar el dataset actualizado
display(df)

,NOMBRE,EDAD,SALARIO,CIUDAD,GENERO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO
0,Ana,58.790698,3.955413e+03,Bogotá,Masculino,Bajo,2018-12-29,4030.026008,1213.936751,ABC12345
1,Maria,58.790698,3.054891e+03,Bogotá,Femenino,alto,2011-07-16,7509.810584,6038.896355,NaN
2,Carlos,58.790698,2.928345e+08,Bogotá,Femenino,Bajo,2022-04-07,9106.362328,6705.724812,NaN
3,Maria,11.000000,4.718402e+03,Bogotá,femenino,medio,2022-10-11,NaN,NaN,XYZ98765
4,Laura,94.000000,7.477876e+07,Cali,masculino,alto,2017-07-11,3102.167244,7570.107277,NaN
...,...,...,...,...,...,...,...,...,...,...
88,Laura,58.790698,9.470361e+08,Bogotá,femenino,NaN,2021-12-15,6284.059343,NaN,NaN
89,Carlos,58.790698,5.124148e+02,Medellín,femenino,alto,2012-01-15,6299.541836,5755.516859,LMN24680
90,Carlos,58.790698,1.407398e+07,Cali,femenino,medio,2023-07-27,1151.975281,916.092328,NaN
91,Laura,58.790698,9.462710e+08,Bogotá,femenino,medio,2013-01-24,NaN,NaN,NaN
92,Laura,9.000000,9.442515e+08,Bogotá,masculino,NaN,2023-07-07,NaN,NaN,ABC12345

# Conversión de variables ordinales

In [13]:
# Convertir los valores de NIVEL a números
df["NIVEL"] = df["NIVEL"].str.strip().str.lower().map({
    "bajo": 1,
    "medio": 2,
    "alto": 3
})

# Mostrar los resultados
display(df)

,NOMBRE,EDAD,SALARIO,CIUDAD,GENERO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO
0,Ana,58.790698,3.955413e+03,Bogotá,Masculino,1.0,2018-12-29,4030.026008,1213.936751,ABC12345
1,Maria,58.790698,3.054891e+03,Bogotá,Femenino,3.0,2011-07-16,7509.810584,6038.896355,NaN
2,Carlos,58.790698,2.928345e+08,Bogotá,Femenino,1.0,2022-04-07,9106.362328,6705.724812,NaN
3,Maria,11.000000,4.718402e+03,Bogotá,femenino,2.0,2022-10-11,NaN,NaN,XYZ98765
4,Laura,94.000000,7.477876e+07,Cali,masculino,3.0,2017-07-11,3102.167244,7570.107277,NaN
...,...,...,...,...,...,...,...,...,...,...
88,Laura,58.790698,9.470361e+08,Bogotá,femenino,NaN,2021-12-15,6284.059343,NaN,NaN
89,Carlos,58.790698,5.124148e+02,Medellín,femenino,3.0,2012-01-15,6299.541836,5755.516859,LMN24680
90,Carlos,58.790698,1.407398e+07,Cali,femenino,2.0,2023-07-27,1151.975281,916.092328,NaN
91,Laura,58.790698,9.462710e+08,Bogotá,femenino,2.0,2013-01-24,NaN,NaN,NaN
92,Laura,9.000000,9.442515e+08,Bogotá,masculino,NaN,2023-07-07,NaN,NaN,ABC12345

# Codificación de variables categóricas

In [14]:
# Convertir GENERO y CIUDAD a variables dummy
df = pd.get_dummies(
    df,
    columns=["GENERO", "CIUDAD"],
    drop_first=True,
    dtype=int
)

# Mostrar el dataset actualizado
df.head(10)

,NOMBRE,EDAD,SALARIO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO,GENERO_Masculino,GENERO_Otro,GENERO_femenino,GENERO_masculino,CIUDAD_Cali,CIUDAD_Medellín
0,Ana,58.790698,3.955413e+03,1.0,2018-12-29,4030.026008,1213.936751,ABC12345,1,0,0,0,0,0
1,Maria,58.790698,3.054891e+03,3.0,2011-07-16,7509.810584,6038.896355,NaN,0,0,0,0,0,0
2,Carlos,58.790698,2.928345e+08,1.0,2022-04-07,9106.362328,6705.724812,NaN,0,0,0,0,0,0
3,Maria,11.000000,4.718402e+03,2.0,2022-10-11,NaN,NaN,XYZ98765,0,0,1,0,0,0
4,Laura,94.000000,7.477876e+07,3.0,2017-07-11,3102.167244,7570.107277,NaN,0,0,0,1,1,0
5,Juan,58.790698,1.894348e+08,NaN,2021-12-29,NaN,NaN,XYZ98765,0,0,0,0,1,0
6,Juan,44.000000,1.407398e+07,2.0,2010-11-21,2780.272641,NaN,ABC12345,0,0,1,0,1,0
7,Laura,76.000000,1.407398e+07,2.0,2013-11-18,NaN,6624.491298,XYZ98765,0,0,0,0,0,0
8,Laura,58.790698,1.937890e+08,1.0,2025-06-02,5356.247710,5852.075127,LMN24680,0,0,1,0,1,0
9,Luis,58.790698,1.407398e+07,2.0,2015-02-08,NaN,2822.485163,NaN,0,0,1,0,0,0

# Escalado de variables numéricas

In [15]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in .\.venv\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in .\.venv\Lib\site-packages (from scikit-learn) (2.5.4)
Requirement already satisfied: scipy>=1.10.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in .\.venv\Lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\.venv\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in .\.venv\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
from sklearn.preprocessing import MinMaxScaler

# Crear el escalador
scaler = MinMaxScaler()

# Escalar las columnas EDAD e INGRESOS
df[["EDAD", "INGRESOS"]] = scaler.fit_transform(
    df[["EDAD", "INGRESOS"]]
)

# Mostrar los resultados
display(df)

,NOMBRE,EDAD,SALARIO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO,GENERO_Masculino,GENERO_Otro,GENERO_femenino,GENERO_masculino,CIUDAD_Cali,CIUDAD_Medellín
0,Ana,0.515708,3.955413e+03,1.0,2018-12-29,0.328719,1213.936751,ABC12345,1,0,0,0,0,0
1,Maria,0.515708,3.054891e+03,3.0,2011-07-16,0.726166,6038.896355,NaN,0,0,0,0,0,0
2,Carlos,0.515708,2.928345e+08,1.0,2022-04-07,0.908518,6705.724812,NaN,0,0,0,0,0,0
3,Maria,0.096491,4.718402e+03,2.0,2022-10-11,NaN,NaN,XYZ98765,0,0,1,0,0,0
4,Laura,0.824561,7.477876e+07,3.0,2017-07-11,0.222743,7570.107277,NaN,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Laura,0.515708,9.470361e+08,NaN,2021-12-15,0.586166,NaN,NaN,0,0,1,0,0,0
89,Carlos,0.515708,5.124148e+02,3.0,2012-01-15,0.587934,5755.516859,LMN24680,0,0,1,0,0,1
90,Carlos,0.515708,1.407398e+07,2.0,2023-07-27,0.000000,916.092328,NaN,0,0,1,0,1,0
91,Laura,0.515708,9.462710e+08,2.0,2013-01-24,NaN,NaN,NaN,0,0,1,0,0,0
92,Laura,0.078947,9.442515e+08,NaN,2023-07-07,NaN,NaN,ABC12345,0,0,0,1,0,0

# Eliminación de registros duplicados

In [17]:
# Eliminar filas duplicadas
df = df.drop_duplicates()

# Reiniciar los índices
df = df.reset_index(drop=True)

# Mostrar el dataset actualizado
display(df)

,NOMBRE,EDAD,SALARIO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO,GENERO_Masculino,GENERO_Otro,GENERO_femenino,GENERO_masculino,CIUDAD_Cali,CIUDAD_Medellín
0,Ana,0.515708,3.955413e+03,1.0,2018-12-29,0.328719,1213.936751,ABC12345,1,0,0,0,0,0
1,Maria,0.515708,3.054891e+03,3.0,2011-07-16,0.726166,6038.896355,NaN,0,0,0,0,0,0
2,Carlos,0.515708,2.928345e+08,1.0,2022-04-07,0.908518,6705.724812,NaN,0,0,0,0,0,0
3,Maria,0.096491,4.718402e+03,2.0,2022-10-11,NaN,NaN,XYZ98765,0,0,1,0,0,0
4,Laura,0.824561,7.477876e+07,3.0,2017-07-11,0.222743,7570.107277,NaN,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Laura,0.515708,9.470361e+08,NaN,2021-12-15,0.586166,NaN,NaN,0,0,1,0,0,0
89,Carlos,0.515708,5.124148e+02,3.0,2012-01-15,0.587934,5755.516859,LMN24680,0,0,1,0,0,1
90,Carlos,0.515708,1.407398e+07,2.0,2023-07-27,0.000000,916.092328,NaN,0,0,1,0,1,0
91,Laura,0.515708,9.462710e+08,2.0,2013-01-24,NaN,NaN,NaN,0,0,1,0,0,0
92,Laura,0.078947,9.442515e+08,NaN,2023-07-07,NaN,NaN,ABC12345,0,0,0,1,0,0

# Creación de nuevas variables

In [18]:
# Calcular la utilidad
df["UTILIDAD"] = df["INGRESOS"] - df["GASTOS"]

# Mostrar el dataset actualizado
display(df)

,NOMBRE,EDAD,SALARIO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO,GENERO_Masculino,GENERO_Otro,GENERO_femenino,GENERO_masculino,CIUDAD_Cali,CIUDAD_Medellín,UTILIDAD
0,Ana,0.515708,3.955413e+03,1.0,2018-12-29,0.328719,1213.936751,ABC12345,1,0,0,0,0,0,-1213.608032
1,Maria,0.515708,3.054891e+03,3.0,2011-07-16,0.726166,6038.896355,NaN,0,0,0,0,0,0,-6038.170189
2,Carlos,0.515708,2.928345e+08,1.0,2022-04-07,0.908518,6705.724812,NaN,0,0,0,0,0,0,-6704.816294
3,Maria,0.096491,4.718402e+03,2.0,2022-10-11,NaN,NaN,XYZ98765,0,0,1,0,0,0,NaN
4,Laura,0.824561,7.477876e+07,3.0,2017-07-11,0.222743,7570.107277,NaN,0,0,0,1,1,0,-7569.884534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Laura,0.515708,9.470361e+08,NaN,2021-12-15,0.586166,NaN,NaN,0,0,1,0,0,0,NaN
89,Carlos,0.515708,5.124148e+02,3.0,2012-01-15,0.587934,5755.516859,LMN24680,0,0,1,0,0,1,-5754.928925
90,Carlos,0.515708,1.407398e+07,2.0,2023-07-27,0.000000,916.092328,NaN,0,0,1,0,1,0,-916.092328
91,Laura,0.515708,9.462710e+08,2.0,2013-01-24,NaN,NaN,NaN,0,0,1,0,0,0,NaN
92,Laura,0.078947,9.442515e+08,NaN,2023-07-07,NaN,NaN,ABC12345,0,0,0,1,0,0,NaN

In [21]:
df = df.fillna(0)

display(df)

C:\Users\USER\AppData\Local\Temp\ipykernel_7508\334260586.py:1: Pandas4Warning: 'int' is not supported as a fill value for str dtype. In a future version, calling fillna with an incompatible value will raise. Explicitly cast to a common dtype before filling.
  df = df.fillna(0)

,NOMBRE,EDAD,SALARIO,NIVEL,FECHA,INGRESOS,GASTOS,CODIGO,GENERO_Masculino,GENERO_Otro,GENERO_femenino,GENERO_masculino,CIUDAD_Cali,CIUDAD_Medellín,UTILIDAD
0,Ana,0.515708,3.955413e+03,1.0,2018-12-29,0.328719,1213.936751,ABC12345,1,0,0,0,0,0,-1213.608032
1,Maria,0.515708,3.054891e+03,3.0,2011-07-16,0.726166,6038.896355,0,0,0,0,0,0,0,-6038.170189
2,Carlos,0.515708,2.928345e+08,1.0,2022-04-07,0.908518,6705.724812,0,0,0,0,0,0,0,-6704.816294
3,Maria,0.096491,4.718402e+03,2.0,2022-10-11,0.000000,0.000000,XYZ98765,0,0,1,0,0,0,0.000000
4,Laura,0.824561,7.477876e+07,3.0,2017-07-11,0.222743,7570.107277,0,0,0,0,1,1,0,-7569.884534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Laura,0.515708,9.470361e+08,0.0,2021-12-15,0.586166,0.000000,0,0,0,1,0,0,0,0.000000
89,Carlos,0.515708,5.124148e+02,3.0,2012-01-15,0.587934,5755.516859,LMN24680,0,0,1,0,0,1,-5754.928925
90,Carlos,0.515708,1.407398e+07,2.0,2023-07-27,0.000000,916.092328,0,0,0,1,0,1,0,-916.092328
91,Laura,0.515708,9.462710e+08,2.0,2013-01-24,0.000000,0.000000,0,0,0,1,0,0,0,0.000000
92,Laura,0.078947,9.442515e+08,0.0,2023-07-07,0.000000,0.000000,ABC12345,0,0,0,1,0,0,0.000000

# Guardado del dataset limpio

In [23]:
# Exportar el DataFrame a un archivo CSV
df.to_csv("datos_limpios.csv", index=False)

print("Archivo datos_limpios.csv exportado correctamente.")

Archivo datos_limpios.csv exportado correctamente.